plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  papers:
    output: false
    permalink: /:collection/:slug:output_ext

images_location: /assets/img

# --- SEO ---

tagline: Personal website of Pragna Mamidipaka
description: "Pragna Mamidipaka is a PhD student in Electrical and Computer Engineering at Carnegie Mellon University, working on systems and networking research with a focus on eBPF frameworks and observability."
logo: &logo /assets/img/logo.png

# Logo is weird, needs to be set as a site-wide default
defaults:
  - scope:
      path: ""
    values:
      image: *logo

author:
  name: Pragna Mamidipaka
  email: pmamidip@andrew.cmu.edu

locale: en_US

# --- SEO ends ---

google_analytics: G-033ZGR8MHH

# Site metadata
title: Pragna Mamidipaka
url: https://pymamid.github.io
baseurl: ""

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: date
timezone: America/New_York